name: Deploy_svl

on: [workflow_dispatch]

jobs:
  scp_to_server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy repo contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SVL_HOST }}
        USERNAME: ${{ secrets.SVL_USER }}
        PORT: ${{ secrets.SVL_PORT }}
        KEY: ${{ secrets.SVL_SSHKEY }}
      with:
        source: "."
        target: ${{ secrets.SVL_SPOTDIR }}
