name: Deploy_avl

on: [workflow_dispatch]

jobs:
  scp_to_server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy repo contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.AVL_HOST }}
        USERNAME: ${{ secrets.AVL_USER }}
        PORT: ${{ secrets.AVL_PORT }}
        KEY: ${{ secrets.AVL_SSHKEY }}
      with:
        source: "."
        target: ${{ secrets.AVL_SPOTDIR }}
